 #config.toml

base_Url="net.ton.dev"
servers=["net.ton.dev"]
message_retries_count=10
message_expiration_timeout=10000
message_expiration_timeout_grow_factor=1.5
message_processing_timeout=40000
wait_for_timeout=40000
access_key=""
out_of_sync_threshold=15000